[package]
name = "ruzit"
version = "1.2.5"
edition = "2024"

[lib]
name = "ruzit"
path = "src/lib.rs"

[[bin]]
name = "ruzitrun"
path = "src/main.rs"

[dependencies]
ruzit-core = { path = "../core" }
mlua = { version = "0.10", features = ["luau", "luau-jit"] }
serde_json = "1"
toml = "0.8"
serde_yaml = "0.9"
tiny_http = "0.12"
ureq = { version = "2", default-features = false, features = ["tls", "gzip"] }
interprocess = "2"
tungstenite = { version = "0.24", default-features = false, features = ["handshake"] }
sysinfo = { version = "0.32", default-features = false, features = ["system"] }
md-5 = "0.10"
aes-gcm = "0.10"
rand = "0.8"
sha1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
blake3 = "1"
hex = "0.4"
base64 = "0.22"
flate2 = "1"
zstd = "0.13"
winit = "0.30"
wgpu = "22"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.3"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "bmp", "gif", "webp"] }
fontdue = "0.9"
dirs = "5"
fbxcel-dom = "0.0.10"
anyhow = "1"
gilrs = "0.10"
rayon = "1"
rodio = { version = "0.20", default-features = false, features = [
    "symphonia-all",
] }
rapier3d = { version = "0.22", features = ["parallel"] }
nalgebra = "0.33"
opus = { version = "0.3", optional = true }
steamworks = { version = "0.11", optional = true }
steamworks-sys = { version = "0.11", optional = true }
cpal = {version = "0.15", optional = true}


[features]
default = ["steam", "voice"]
steam = ["dep:steamworks", "dep:steamworks-sys"]
voice = ["dep:opus", "dep:cpal"]

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_System_LibraryLoader",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Storage_FileSystem",
    "Win32_Security",
] }
