[workspace]
resolver = "2"
members = ["core", "runtime", "cli"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
overflow-checks = false
debug = false

[profile.dev]
opt-level = 1
debug = 1

[profile.dev.package."*"]
opt-level = 3

[profile.bench]
inherits = "release"
